# DataSource Config
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/user-center
  application:
    name: user-center-back
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 共享session至redis
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
server:
  port: 8080
  servlet:
    #    接口访问前缀
    context-path: /api
    session:
      cookie:
        domain: localhost
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-footer: true
    enable-footer-custom: true
    footer-custom-content: Apache License 2.0 | Copyright  2019-[浙江八一菜刀研究基地](https://gitee.com/xiaoym/knife4j)
  openapi:
    title: 用户中心接口文档
    description: 用户中心接口文档
    email: crane.resigned@qq.com
    concat: Crane Resigned
    url: https://github.com/Crane-R/user-center-back
    version: v0.1.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.knife4j.demo.new3